---
title: "FASOM Results"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: TRUE
    toc_float:
      collapsed: TRUE
    toc_depth: 3
    code_folding: "hide"
    number_sections: TRUE
---
# Setup
```{r setup, include=FALSE}
devtools::load_all(".")
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 10, fig.height = 6, dpi = 150)
```

```{r process-data, include=FALSE}
# Process GDX files to standard CSV format (skips if files already exist).
# Set force = TRUE to re-process after data updates.
process_fasom_gdx(force = FALSE)
```

```{r helpers}

```

## Data Access

```{r load-data, message=FALSE, warning=FALSE}
ozone_crop_2015  <- read_dataset("cropW126ryg.csv",  model_filter = "OzoneRYG_2015_v4")  
ozone_for_2015  <- read_dataset("forW126ryg.csv",  model_filter = "OzoneRYG_2015_v4")

ozone_crop_2026  <- read_dataset("cropW126ryg.csv",  model_filter = "OzoneRYG_2026_v4")
ozone_for_2026  <- read_dataset("forW126ryg.csv",  model_filter = "OzoneRYG_2026_v4")
```

```{r}
df <- bind_rows(ozone_crop_2015, ozone_crop_2026)

plot <- telescope::plotting(
  df = df,
  figtype = "bar",
  fb_title_name = "Ozone-Related Yield Gain by Region",
  fb_figure_no = "",
  fb_x = "region",
  fb_y = "value",
  fb_color = "model",
  fb_regions = c(
    "CB",
    "GP",
    "LS",
    "NE",
    "RM",
    "PSW",
    "PNWW",
    "PNWE",
    "SC",
    "SE",
    "SW"
  ),
  fb_models = c("OzoneRYG_2015_v4", "OzoneRYG_2026_v4"),
  fb_years = "2020-2100",
  fb_scenarios = "75ppb",
  fb_variable = c("Cotton", "Corn", "wheat", "Soybeans"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Region",
  fb_y_title = "Value",
  fb_y_units = "fraction",
  fb_subtitle = "Major field crops, W126 exposure = 75ppb",
  fb_caption = "Source: FASOM/OzoneRYG_2015_v4/cropW126ryg.csv, FASOM/OzoneRYG_2026_v4/cropW126ryg.csv"
)

print(plot)
```

