---
title: "FASOM Results"
date: "`r Sys.Date()`"
output:
  powerpoint_presentation:
    reference_doc: template.pptx
  html_document:
    theme: united
    toc: TRUE
    toc_float:
      collapsed: FALSE
    toc_depth: 3
    code_folding: "hide"
    number_sections: TRUE
---
```{r setup, include=FALSE}
devtools::load_all(".")
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.width = 11, fig.height = 7, dpi = 150)

knitr::opts_chunk$set(
  fig.path = paste0("saved_images_", Sys.Date(), "/"),  # Saves all images to a folder named 'saved_images'
  dev = "png",                 # Formats: "png", "jpg", "pdf", or "svg"
  dpi = 400                    # Ensures high-quality images
)
```

```{r process-data, include=FALSE}
# Process GDX files to standard CSV format (skips if files already exist).
# Set force = TRUE to re-process after data updates.
process_fasom_gdx(force = FALSE)
```

```{r helpers}
year_range <- "2020-2060"
```

# Slides

## Land Use Totals

```{r, land-use-totals}
df <- 
  telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/total_acres.csv") %>% 
  group_by(scenario, variable, year, datasrc, unit) %>%
  summarize(value = sum(value, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(region = "Total") %>% 
  mutate(value = value/1000) %>% 
  mutate(units = "million acres")

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Total Acreage by Land Type",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "Total",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c("Cropland", "Pasture", "CropLand_Pasture", "ForestLand"),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_title = "Value",
  fb_y_units = "million acres",
  fb_subtitle = "BASE, 75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/total_acres.csv",
  fb_view = "levels"
)

print(plot)
```

## Cumulative Land Transfer

```{r, cumulative-land-transfer}
cap_first <- function(x) {
  paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))
}

df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/LandTransfer_Cumulative.csv") %>% 
  mutate(change = case_when(stringr::str_starts(variable, stringr::coll("To", ignore_case = TRUE)) ~ "Loss",
                               stringr::str_starts(variable, stringr::coll("From", ignore_case = TRUE)) ~ "Gain",
                               TRUE ~ "Flag")) %>% 
  mutate(variable = case_when(stringr::str_starts(variable, stringr::coll("To", ignore_case = TRUE)) ~ cap_first(gsub("To", "", cap_first(variable), ignore.case = TRUE)),
                              stringr::str_starts(variable, stringr::coll("From", ignore_case = TRUE)) ~ cap_first(gsub("From", "", cap_first(variable), ignore.case = TRUE)),
                               TRUE ~ "Flag")) %>% 
  mutate(value = case_when(change == "Loss" ~ -value,
                           TRUE ~ value)) %>% 
  mutate(variable = case_when(variable == "Crop" ~ "Cropland",
                              TRUE ~ variable)) %>% 
  group_by(scenario, variable, year, datasrc, unit, change, land_from) %>%
  summarize(value = sum(value, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(region = "Total")

plot <- telescope::plotting(
  df = df,
  figtype = "stacked_bar",
  fb_title_name = "Cumulative Land Transfers",
  fb_subtitle = "Baseline scenario",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "variable",
  fb_regions = "Total",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE"), 
  fb_variable = c(
    "CroplandPasture",
    "CRPProgram",
    "Cropland",
    "Forest",
    "Pasture", 
    "Development"
  ),
  fb_facet1 = "land_from",
  fb_labels = TRUE,
  fb_y_title = "Value",
  fb_y_units = "thousand acres",
  fb_options = "Start y axis at 0",
  fb_view = "levels",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/LandTransfer_Cumulative.csv"
)

print(plot)
```


## Crops
### Crop Harvested Area

```{r, crop-harvested-area}
df <- 
  read_dataset("temphere.csv",  model_filter = "2026_IASD_RYG_v4_2026") %>% 
  dplyr::filter(category %in% "ALL") %>% 
  dplyr::filter(region %in% "US") %>% 
  mutate(region = "Total")

df_wheat <- df %>% 
  dplyr::filter(variable %in% c(
    "DurumWheat",
    "SoftWhiteWheat",
    "HardRedWinterWheat",
    "SoftRedWinterWheat",
    "HardRedSpringWheat"
  )) %>% 
  group_by(year, country, region, category, scenario, entry, model) %>% 
  summarize(value = sum(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(variable = "Wheat")

df <- bind_rows(df, df_wheat)
  

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Difference in Crop Harvested Acreage",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "Total",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = c("Corn", "Cotton", "Rice", "Soybeans", "Wheat"),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_title = "Difference from baseline (thousand acres)",
  fb_subtitle = "2020-2060 US difference from baseline; cotton, wheat, corn, rice, and soybeans",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/temphere.csv", 
  fb_view = "diff",
  fb_hline0 = TRUE
)

print(plot)
```

### Crop Production

```{r, crop-production}
df_raw <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/n_acompareBALANCEP.csv") %>% 
  dplyr::filter(variable %in% c("Production"))

df_wheat <- df_raw %>% 
  dplyr::filter(commodity %in% c(
    "DurumWheat",
    "SoftWhiteWheat",
    "HardRedWinterWheat",
    "SoftRedWinterWheat",
    "HardRedSpringWheat"
  )) %>% 
  group_by(year, variable, scenario, entry, model) %>% 
  summarize(value = sum(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(commodity = "Wheat")

df <- bind_rows(df_raw, df_wheat) %>% 
  dplyr::filter(commodity %in% c("Rice", "Cotton", "Soybeans", "Corn", "Wheat"))

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Major Crop Production",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2100",
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = "Production",
  fb_facet1 = "commodity",
  fb_options = "Start y axis at 0, Aggregate variables",
  fb_x_title = "Year",
  fb_y_title = "Production change (units produced)",
  fb_subtitle = "Relative to baseline",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/n_acompareBALANCEP.csv",
  fb_hline0 = TRUE,
  fb_view = "diff"
)

print(plot)
```

### Crop Price

```{r, crop-price}
df_raw <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/n_acompareBALANCEP.csv") %>% 
  dplyr::filter(variable %in% c("PriceX100"))

df_wheat <- df_raw %>% 
  dplyr::filter(commodity %in% c(
    "DurumWheat",
    "SoftWhiteWheat",
    "HardRedWinterWheat",
    "SoftRedWinterWheat",
    "HardRedSpringWheat"
  )) %>% 
  group_by(year, variable, scenario, entry, model) %>% 
  summarize(value = sum(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(commodity = "Wheat")

df <- bind_rows(df_raw, df_wheat) %>% 
  dplyr::filter(commodity %in% c("Rice", "Cotton", "Soybeans", "Corn", "Wheat"))

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Major Crop Prices",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2100",
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = "PriceX100",
  fb_facet1 = "commodity",
  fb_options = "Start y axis at 0, Aggregate variables",
  fb_x_title = "Year",
  fb_y_title = "Percent difference from baseline price ($/unit)",
  fb_subtitle = "Relative to baseline",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/n_acompareBALANCEP.csv",
  fb_hline0 = TRUE,
  fb_view = "pct"
)

print(plot)
```

## Forest
### Forest Area

```{r, forest-area}

df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/totalforacres.csv") %>%
  group_by(scenario, variable, year, datasrc, unit) %>%
  summarize(value = sum(value, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(region = "Total") %>% 
  mutate(value = value/1000) %>% 
  mutate(units = "million acres")

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Forest Acres",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "Total",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2060",
  fb_scenarios = NULL,
  fb_variable = c(
    "Forest_Hardwood",
    "Planted_Pine",
    "Planted_Doug-fir",
    "Forest_Pine",
    "Forest_Doug-fir",
    "Forest_Softwood",
    "Planted_Softwood",
    "Forest_OakPine",
    "Forest_Softwood"
  ),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_units = "million acres",
  fb_subtitle = "All scenarios",
  fb_y_title = "Forest area",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/totalforacres.csv",
  fb_view = "levels"
)

print(plot)
```

### Forest Production

```{r, forest-production}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/Manufacturing_Output.csv") %>% 
  mutate(variable = case_when(
    variable == "SW_Plywood" ~ "Plywood",
    variable == "HW_Plywood" ~ "Plywood",
    variable == "HW_Lumber" ~ "Lumber",
    variable == "SW_Lumber" ~ "Lumber",
    variable == "MDF" ~ "Panels",
    variable == "OSB" ~ "Panels",
    variable == "OthPanels" ~ "Panels",
    variable == "Tissue" ~ "Paper",
    variable == "Pulp_Mech" ~ "Paper",
    variable == "Pulp_Chem" ~ "Paper",
    variable == "Newsprint" ~ "Paper",
    variable == "P_W_Paper" ~ "Paper",
    variable == "Paperboard" ~ "Paper",
    TRUE ~ variable
  )) %>% 
  dplyr::filter(!(variable %in% c("BioPower", "For_Pellets"))) %>% 
  group_by(scenario, year, variable, model, unit) %>% 
  summarize(value = sum(value, na.rm = TRUE)) %>% 
  ungroup()

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Forest Manufacturing Output",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "Lumber",
    "Plywood",
    "Panels",
    "Paper"
  ),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_title = "Production percent change (units produced)",
  fb_subtitle = "BASE, 75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/Manufacturing_Output.csv",
  fb_view = "pct",
  fb_hline0 = TRUE
)

print(plot)
```

### Forest Price

```{r, forest-price}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/for_product_price.csv") %>% 
  mutate(variable = case_when(
    variable == "SW_Plywood" ~ "Plywood",
    variable == "HW_Plywood" ~ "Plywood",
    variable == "HW_Lumber" ~ "Lumber",
    variable == "SW_Lumber" ~ "Lumber",
    variable == "MDF" ~ "Panels",
    variable == "OSB" ~ "Panels",
    variable == "OthPanels" ~ "Panels",
    variable == "Tissue" ~ "Paper",
    variable == "Pulp_Mech" ~ "Paper",
    variable == "Pulp_Chem" ~ "Paper",
    variable == "Newsprint" ~ "Paper",
    variable == "P_W_Paper" ~ "Paper",
    variable == "Paperboard" ~ "Paper",
    TRUE ~ variable
  )) %>% 
  dplyr::filter(!(variable %in% c("BioPower", "For_Pellets"))) %>% 
  group_by(scenario, year, variable, model, unit) %>% 
  summarize(value = sum(value, na.rm = TRUE)) %>% 
  ungroup()

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Forest Commodity Prices",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "Lumber",
    "Plywood",
    "Panels",
    "Paper"
  ),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_units = "$/unit",
  fb_y_title = "Percent change in price",
  fb_subtitle = "BASE, 75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/for_product_price.csv",
  fb_view = "pct",
  fb_hline0 = TRUE
)

print(plot)
```

## Welfare

```{r, welfare-bar}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/n_wcomparesummaryAnn40.csv") %>% 
  dplyr::filter(category %in% "US") %>% 
  mutate(variable = case_when(variable == "US_dom_demand" ~ "Consumer",
                              variable == "producer" ~ "Producer",
                              variable == "Process" ~ "Processing",
                              TRUE ~ variable)) %>% 
  mutate(subcategory = case_when(subcategory == "Ag" ~ "Agriculture",
                                 subcategory == "forest" ~ "Forestry",
                                 TRUE ~ subcategory)) %>% 
  dplyr::filter(!(variable %in% c("grtotal")))

df_total <- df %>% 
  group_by(category, subcategory, model) %>% 
  mutate(base_sum = sum(value[scenario == "BASE"], na.rm = TRUE)) %>% 
  group_by(category, subcategory, scenario, model) %>% 
  summarize(value = sum(value, na.rm = TRUE) - base_sum) %>%
  ungroup() %>% 
  mutate(variable = "Total") %>% 
  dplyr::filter(!(scenario %in% c("BASE"))) %>% 
  unique() %>% 
  mutate(label = format(value, digits = 5)) %>% 
  mutate(value = value + value*0.02 + 5000)

plot <- telescope::plotting(
  df = df,
  figtype = "stacked_bar",
  fb_title_name = "Annualized (2020-2040) Welfare Difference from Baseline Including Processing",
  fb_figure_no = "",
  fb_x = "scenario",
  fb_y = "value",
  fb_color = "variable",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2100",
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = c("Consumer", "Producer", "Processing"),
  fb_facet1 = "subcategory",
  fb_x_title = "Scenario",
  fb_y_title = "Welfare change",
  fb_y_units = "$",
  fb_subtitle = "75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/n_wcomparesummaryAnn40.csv",
  fb_facet_scales = "fixed",
  fb_labels = TRUE,
  fb_view = "diff"
) +
  geom_label(data = df_total, aes(label = label), show.legend = FALSE) 

print(plot)
```


# Other Slides
## Ozone Inputs

```{r load-ozone-data, message=FALSE, warning=FALSE, include=FALSE}
ozone_crop_2015_updated  <- read_dataset("crop_ryg_summary.csv",  model_filter = "2026_IASD_RYG_v4_15O26P")  
ozone_for_2015_updated    <- read_dataset("for_ryg_summary.csv",  model_filter = "2026_IASD_RYG_v4_15O26P")

ozone_crop_2015  <- read_dataset("crop_ryg_summary.csv",  model_filter = "2026_IASD_RYG_v4_2015")  
ozone_for_2015  <- read_dataset("for_ryg_summary.csv",  model_filter = "2026_IASD_RYG_v4_2015")

ozone_crop_2026  <- read_dataset("crop_ryg_summary.csv",  model_filter = "2026_IASD_RYG_v4_2026")
ozone_for_2026  <- read_dataset("for_ryg_summary.csv",  model_filter = "2026_IASD_RYG_v4_2026")

ozone_crop_for_inputs <- c("2026_IASD_RYG_v4_15O26P", "2026_IASD_RYG_v4_2015", "2026_IASD_RYG_v4_2026")
```

### Models

```{r, ozone-yield}
df <- 
  bind_rows(ozone_crop_2015_updated, ozone_crop_2015, ozone_crop_2026) %>% 
  mutate(variable = case_when(variable == "wheat" ~ "Wheat",
                              TRUE ~ variable))

plot <- telescope::plotting(
  df = df,
  figtype = "bar",
  fb_title_name = "Ozone-Related Yield Gain by Region",
  fb_figure_no = "",
  fb_x = "region",
  fb_y = "value",
  fb_color = "model",
  fb_regions = c(
    "CB",
    "GP",
    "LS",
    "NE",
    "RM",
    "PSW",
    "PNWW",
    "PNWE",
    "SC",
    "SE",
    "SW",
    "Total"
  ),
  fb_models = ozone_crop_for_inputs,
  fb_years = "2020-2100",
  fb_scenarios = "75ppb",
  fb_variable = c("Cotton", "Corn", "Wheat", "Soybeans"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Region",
  fb_y_title = "Value",
  fb_y_units = "percent",
  fb_subtitle = "Major field crops, W126 exposure = 75ppb",
  fb_caption = paste0("Source: ", paste0(unique(df$datasrc), collapse = ", "))
) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  scale_y_continuous(labels = scales::label_percent())

print(plot)

# TODO: Add annotation for missing Wheat total
```

```{r, ozone-growth}
df <- 
  bind_rows(ozone_for_2015_updated, ozone_for_2015, ozone_for_2026) %>% 
  mutate(variable = case_when(stringr::str_starts(variable, "Forest") ~ gsub("Forest_", "", variable),
                              TRUE ~ variable))

plot <- telescope::plotting(
  df = df,
  figtype = "bar",
  fb_title_name = "Ozone-Related Growth Gain by Region",
  fb_figure_no = "",
  fb_x = "region",
  fb_y = "value",
  fb_color = "model",
  fb_regions = c(
    "CB",
    "GP",
    "LS",
    "NE",
    "RM",
    "PSW",
    "PNWW",
    "PNWE",
    "SC",
    "SE",
    "SW",
    "Total"
  ),
  fb_models = ozone_crop_for_inputs,
  fb_years = "2020-2100",
  fb_scenarios = "75ppb",
  fb_variable = c("Hardwood", "Pine", "Doug-fir", "Softwood"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Region",
  fb_y_title = "Value",
  fb_y_units = "percent",
  fb_subtitle = "Major forest types, W126 exposure = 75ppb",
  fb_caption = paste0("Source: ", paste0(unique(df$datasrc), collapse = ", "))
) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  scale_y_continuous(labels = scales::label_percent())

print(plot)
```
### Scenarios

```{r, ozone-yield-scenario}
df <- 
  bind_rows(ozone_crop_2026) %>% 
  mutate(variable = case_when(variable == "wheat" ~ "Wheat",
                              TRUE ~ variable))

plot <- telescope::plotting(
  df = df,
  figtype = "bar",
  fb_title_name = "Ozone-Related Yield Gain by Region",
  fb_figure_no = "",
  fb_x = "region",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = c(
    "CB",
    "GP",
    "LS",
    "NE",
    "RM",
    "PSW",
    "PNWW",
    "PNWE",
    "SC",
    "SE",
    "SW",
    "Total"
  ),
  fb_models = ozone_crop_for_inputs,
  fb_years = "2020-2100",
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = c("Cotton", "Corn", "Wheat", "Soybeans"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Region",
  fb_y_title = "Value",
  fb_y_units = "percent",
  fb_subtitle = "Major field crops",
  fb_caption = paste0("Source: ", paste0(unique(df$datasrc), collapse = ", "))
) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  scale_y_continuous(labels = scales::label_percent())

print(plot)

# TODO: Add annotation for missing Wheat total
```

```{r, ozone-growth-scenario}
df <- 
  bind_rows(ozone_for_2026) %>% 
  mutate(variable = case_when(stringr::str_starts(variable, "Forest") ~ gsub("Forest_", "", variable),
                              TRUE ~ variable))

plot <- telescope::plotting(
  df = df,
  figtype = "bar",
  fb_title_name = "Ozone-Related Growth Gain by Region",
  fb_figure_no = "",
  fb_x = "region",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = c(
    "CB",
    "GP",
    "LS",
    "NE",
    "RM",
    "PSW",
    "PNWW",
    "PNWE",
    "SC",
    "SE",
    "SW",
    "Total"
  ),
  fb_models = ozone_crop_for_inputs,
  fb_years = "2020-2100",
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = c("Hardwood", "Pine", "Doug-fir", "Softwood"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Region",
  fb_y_title = "Value",
  fb_y_units = "percent",
  fb_subtitle = "Major forest types",
  fb_caption = paste0("Source: ", paste0(unique(df$datasrc), collapse = ", "))
) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  scale_y_continuous(labels = scales::label_percent())

print(plot)
```

## CMAQ Inputs

```{r load-exposure-data, message=FALSE, warning=FALSE, include=FALSE}
ozone_vals_2015_updated  <- read_dataset("crop_ozone_vals.csv",  model_filter = "2026_IASD_RYG_v4_15O26P")  
ozone_vals_2015  <- read_dataset("crop_ozone_vals.csv",  model_filter = "2026_IASD_RYG_v4_2015")  
ozone_vals_2026  <- read_dataset("crop_ozone_vals.csv",  model_filter = "2026_IASD_RYG_v4_2026")
ozone_vals_inputs <- c("2026_IASD_RYG_v4_15O26P", "2026_IASD_RYG_v4_2015", "2026_IASD_RYG_v4_2026")
```

```{r, cmaq-inputs-comparison}
df <- bind_rows(ozone_vals_2015_updated, ozone_vals_2015, ozone_vals_2026) %>% 
  mutate(variable = case_when(variable == "wheat" ~ "Wheat",
                              TRUE ~ variable))

plot <- telescope::plotting(
  df = df,
  figtype = "bar",
  fb_title_name = "CMAQ Input Data",
  fb_figure_no = "",
  fb_x = "region",
  fb_y = "value",
  fb_color = "model",
  fb_regions = c(
    "CB",
    "GP",
    "LS",
    "NE",
    "RM",
    "PSW",
    "PNWW",
    "PNWE",
    "SC",
    "SE",
    "SW"
  ),
  fb_models = c(
    "2026_IASD_RYG_v4_15O26P",
    "2026_IASD_RYG_v4_2015",
    "2026_IASD_RYG_v4_2026"
  ),
  fb_years = "2020-2100",
  fb_scenarios = c("75ppb"),
  fb_variable = c("Corn", "Soybeans", "Cotton", "Wheat"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Region",
  fb_y_units = "ppm-hr",
  fb_y_title = "Ozone Exposure",
  fb_subtitle = "Major field crops, W126 exposure = 75ppb",
  fb_caption = paste0("Source: ", paste0(unique(df$datasrc), collapse = ", "))
) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

print(plot)
```

```{r, cmaq-inputs-scenarios}
df <- bind_rows(ozone_vals_2026) %>% 
  mutate(variable = case_when(variable == "wheat" ~ "Wheat",
                              TRUE ~ variable))

plot <- telescope::plotting(
  df = df,
  figtype = "bar",
  fb_title_name = "CMAQ Input Data",
  fb_figure_no = "",
  fb_x = "region",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = c(
    "CB",
    "GP",
    "LS",
    "NE",
    "RM",
    "PSW",
    "PNWW",
    "PNWE",
    "SC",
    "SE",
    "SW"
  ),
  fb_models = c(
    "2026_IASD_RYG_v4_2026"
  ),
  fb_years = "2020-2100",
  fb_scenarios = c("75ppb", "70ppb", "65ppb", "BASE"),
  fb_variable = c("Corn", "Soybeans", "Cotton", "Wheat"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Region",
  fb_y_units = "ppm-hr",
  fb_y_title = "Ozone Exposure",
  fb_subtitle = "Major field crops, W126 exposure = 75ppb",
  fb_caption = paste0("Source: ", paste0(unique(df$datasrc), collapse = ", "))
) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

print(plot)
```

## Crop Harvested Acreage

```{r, crop-acreage}
df <- 
  read_dataset("temphere.csv",  model_filter = "2026_IASD_RYG_v4_2026") %>% 
  dplyr::filter(category %in% "ALL")

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Crop Harvested Acreage",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "US",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c("Corn", "Rice", "Soybeans"),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_title = "Thousand Acres",
  fb_subtitle = "2020-2060 US total, corn, rice, and soybeans",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/temphere.csv"
)

print(plot)

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Crop Harvested Acreage",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "US",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "DurumWheat",
    "SoftWhiteWheat",
    "HardRedWinterWheat",
    "SoftRedWinterWheat",
    "HardRedSpringWheat"
  ),
  fb_x_title = "Year",
  fb_y_title = "Thousand Acres",
  fb_facet1 = "variable",
  fb_subtitle = "2020-2060 US total, wheat",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/temphere.csv",
)

print(plot)

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Crop Harvested Acreage",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "US",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "DurumWheat",
    "SoftWhiteWheat",
    "HardRedWinterWheat",
    "SoftRedWinterWheat",
    "HardRedSpringWheat"
  ),
  fb_options = "Aggregate variables",
  fb_x_title = "Year",
  fb_y_title = "Thousand Acres",
  fb_subtitle = "2020-2060 US total, wheat",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/temphere.csv",
)

print(plot)

# TODO: Add 70ppb and 65ppb
```

## Comparison Indices

```{r, indices}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/comparison_index.csv")

plot <- telescope::plotting(
  df = dplyr::filter(df, .data[["category"]] %in% "Production"),
  figtype = "timeseries",
  fb_title_name = "FASOM Production Index",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "AllCrops",
    "AllFarmProd",
    "AllLivestock",
    "AllProcessed",
    "Meats",
    "MixedFeeds"
  ),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_title = "Production Index",
  fb_y_units = "BASE = 100",
  fb_subtitle = "All scenarios",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/comparison_index.csv"
)

print(plot)

plot <- telescope::plotting(
  df = dplyr::filter(df, .data[["category"]] %in% "Price"),
  figtype = "timeseries",
  fb_title_name = "FASOM Price Index",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "AllCrops",
    "AllFarmProd",
    "AllLivestock",
    "AllProcessed",
    "Meats",
    "MixedFeeds"
  ),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_title = "Price Index",
  fb_y_units = "BASE = 100",
  fb_subtitle = "All scenarios; Fisher ideal index",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/comparison_index.csv"
)

print(plot)
```

## Welfare

```{r, ag_welfare}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/n_wcomparesummary.csv") %>% 
  mutate(variable = case_when(variable == "grtotal" ~ "Total US",
                              variable == "Process" ~ "Processing",
                              variable == "producer" ~ "Producer",
                              variable == "US_dom_demand" ~ "Consumer", 
                              TRUE ~ variable))

plot <- telescope::plotting(
  df = dplyr::filter(df, .data[["category"]] %in% "gtotal"),
  figtype = "timeseries",
  fb_title_name = "Agricultural Welfare % Change from Baseline",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = c("Consumer", "Producer", "Processing", "Total US"),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Year",
  fb_y_title = "% change from baseline",
  fb_subtitle = "75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/n_wcomparesummary.csv",
  fb_hline0 = TRUE,
  fb_pct_change = TRUE
)

print(plot)
```

```{r, forestry_welfare}
df <- telescope::read_dataset(
  c(
    "FASOM/2026_IASD_RYG_v4_2026/n_wcompareforconssurplus.csv",
    "FASOM/2026_IASD_RYG_v4_2026/n_wcompareforprodsurplus.csv"
  )
) %>% 
  dplyr::filter(category %in% "forestry") %>% 
  mutate(entry = case_when(entry == "n_wcompareforconssurplus" ~ "Consumer Surplus",
                           entry == "n_wcompareforprodsurplus" ~ "Producer Surplus",
                           TRUE ~ entry))

df_aggregate <- df %>% 
  group_by(year, variable, region, category, subcategory, scenario, model) %>% 
  summarise(value = sum(value, na.rm = TRUE)) %>% 
  mutate(entry = "Total (Consumer + Producer)")

df <- bind_rows(df, df_aggregate)

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Forest Welfare % Change from Baseline",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "US",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = "US_dom_demand",
  fb_facet1 = "entry",
  fb_options = "Start y axis at 0",
  fb_x_title = "Year",
  fb_y_title = "% change from baseline",
  fb_subtitle = "75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/n_wcompareforconssurplus.csv, FASOM/2026_IASD_RYG_v4_2026/n_wcompareforprodsurplus.csv",
  fb_hline0 = TRUE,
  fb_pct_change = TRUE
)

print(plot)
```

```{r, welfare-bars}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/n_wcomparesummaryAnn40.csv") %>% 
  dplyr::filter(category %in% "US") %>% 
  mutate(variable = case_when(variable == "US_dom_demand" ~ "Consumer",
                              variable == "producer" ~ "Producer",
                              variable == "Process" ~ "Processing",
                              TRUE ~ variable)) %>% 
  mutate(subcategory = case_when(subcategory == "Ag" ~ "Agriculture",
                                 subcategory == "forest" ~ "Forestry",
                                 TRUE ~ subcategory))

plot <- telescope::plotting(
  df = df,
  figtype = "stacked_bar",
  fb_title_name = "Annualized (2020-2040) Welfare Difference from Baseline Excluding Processing",
  fb_figure_no = "",
  fb_x = "scenario",
  fb_y = "value",
  fb_color = "variable",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2100",
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = c("Consumer", "Producer"),
  fb_facet1 = "subcategory",
  fb_x_title = "Scenario",
  fb_y_title = "Welfare change",
  fb_y_units = "$",
  fb_subtitle = "75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/n_wcomparesummaryAnn40.csv",
  fb_facet_scales = "fixed",
  fb_labels = TRUE,
  fb_view = "diff"
)

print(plot)

plot <- telescope::plotting(
  df = df,
  figtype = "stacked_bar",
  fb_title_name = "Annualized (2020-2040) Welfare Difference from Baseline Including Processing",
  fb_figure_no = "",
  fb_x = "scenario",
  fb_y = "value",
  fb_color = "variable",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2100",
  fb_scenarios = c("75ppb", "70ppb", "65ppb"),
  fb_variable = c("Consumer", "Producer", "Processing"),
  fb_facet1 = "subcategory",
  fb_x_title = "Scenario",
  fb_y_title = "Welfare change",
  fb_y_units = "$",
  fb_subtitle = "75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/n_wcomparesummaryAnn40.csv",
  fb_facet_scales = "fixed",
  fb_labels = TRUE,
  fb_view = "diff"
)

print(plot)
```

## Forest Acreage

```{r, forest-acreage-dep}
# TODO: Check how this should be aggregated
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/totalforacres.csv") %>%
  group_by(scenario, variable, year, datasrc, unit) %>%
  summarize(value = sum(value, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(region = "Total") %>% 
  mutate(value = value/1000) %>% 
  mutate(units = "million acres")

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Forest Acres",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "Total",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2060",
  fb_scenarios = NULL,
  fb_variable = c(
    "Forest_Hardwood",
    "Planted_Pine",
    "Planted_Doug-fir",
    "Forest_Pine",
    "Forest_Doug-fir",
    "Forest_Softwood",
    "Planted_Softwood",
    "Forest_OakPine",
    "Forest_Softwood"
  ),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_units = "million acres",
  fb_subtitle = "All scenarios",
  fb_y_title = "Forest area",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/totalforacres.csv",
  fb_view = "levels"
)

print(plot)
```

```{r, forest-acreage-single}
# TODO: Check how this should be aggregated
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/totalforacres.csv") %>%
  group_by(scenario, category, year, datasrc, unit) %>%
  summarize(value = sum(value, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(region = "Total") %>% 
  mutate(value = value/1000) %>% 
  mutate(units = "million acres") %>% 
  mutate(variable = "Forest Land") %>% 
  dplyr::filter(category %in% "private") %>% 
  mutate(category = "Private")

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Private Forest Land",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "Total",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2060",
  fb_scenarios = NULL,
  fb_variable = c(
    "Forest Land"
  ),
  fb_facet1 = "category",
  fb_x_title = "Year",
  fb_y_units = "million acres",
  fb_subtitle = "All scenarios",
  fb_y_title = "Forest area",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/totalforacres.csv",
  fb_view = "levels"
)

print(plot)

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "FASOM Private Forest Land",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = "Total",
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = "2020-2060",
  fb_scenarios = NULL,
  fb_variable = c(
    "Forest Land"
  ),
  fb_facet1 = "category",
  fb_x_title = "Year",
  fb_y_units = "% change from baseline",
  fb_subtitle = "All scenarios, % difference from baseline",
  fb_y_title = "Forest area",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/totalforacres.csv",
  fb_view = "pct"
)

print(plot)
```

## Forest Products

```{r, for_prod_price}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/for_product_price.csv")

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Forest Commodity Prices",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "SW_Lumber",
    "HW_Lumber",
    "SW_Plywood",
    "HW_Plywood",
    "OSB",
    "OthPanels",
    "MDF",
    "For_Pellets",
    "Newsprint",
    "P_W_Paper",
    "Paperboard",
    "Tissue"
  ),
  fb_facet1 = "variable",
  fb_options = "Start y axis at 0",
  fb_x_title = "Year",
  fb_y_units = "$/unit",
  fb_y_title = "Value",
  fb_subtitle = "BASE, 75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/for_product_price.csv",
  fb_view = "levels"
)

print(plot)
```

```{r, for_prod_mfg}
df <- telescope::read_dataset("FASOM/2026_IASD_RYG_v4_2026/Manufacturing_Output.csv")

plot <- telescope::plotting(
  df = df,
  figtype = "timeseries",
  fb_title_name = "Forest Manufacturing Output",
  fb_figure_no = "",
  fb_x = "year",
  fb_y = "value",
  fb_color = "scenario",
  fb_regions = NULL,
  fb_models = "2026_IASD_RYG_v4_2026",
  fb_years = year_range,
  fb_scenarios = c("BASE", "75ppb", "70ppb", "65ppb"),
  fb_variable = c(
    "SW_Lumber",
    "HW_Lumber",
    "SW_Plywood",
    "HW_Plywood",
    "OthPanels",
    "OSB",
    "MDF",
    "For_Pellets",
    "Newsprint",
    "P_W_Paper",
    "Paperboard",
    "Tissue",
    "Pulp_Chem",
    "Pulp_Mech",
    "BioPower"
  ),
  fb_facet1 = "variable",
  fb_x_title = "Year",
  fb_y_title = "Units",
  fb_subtitle = "BASE, 75ppb, 70ppb, 65ppb",
  fb_caption = "Source: FASOM/2026_IASD_RYG_v4_2026/Manufacturing_Output.csv",
  fb_view = "levels"
)

print(plot)
```